'use client'

import { useState } from 'react'

export default function Reports({ group, members, contributions, payouts }) {
  const [generating, setGenerating] = useState(null)

  const currentMonth = new Date().toLocaleString('default', { month: 'long', year: 'numeric' })
  const currentYear = new Date().getFullYear()

  async function loadJsPDF() {
    const { jsPDF } = await import('jspdf')
    return jsPDF
  }

  function addHeader(doc, title, subtitle) {
    // Header background
    doc.setFillColor(27, 58, 87) // navy
    doc.rect(0, 0, 210, 35, 'F')

    // Logo placeholder circle
    doc.setFillColor(29, 158, 117) // brand green
    doc.circle(20, 17, 8, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('SS', 16.5, 20.5)

    // Title
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('StokSync', 33, 14)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text('by Echelon Crest (PTY) LTD · Reg. 2026/420468/07', 33, 21)
    doc.text('www.stoksync.co.za', 33, 27)

    // Report title
    doc.setTextColor(27, 58, 87)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(title, 14, 50)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(subtitle, 14, 57)

    // Divider
    doc.setDrawColor(29, 158, 117)
    doc.setLineWidth(0.5)
    doc.line(14, 61, 196, 61)

    return 68 // return Y position after header
  }

  function addFooter(doc, pageNum) {
    const pageHeight = doc.internal.pageSize.height
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.3)
    doc.line(14, pageHeight - 18, 196, pageHeight - 18)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.setFont('helvetica', 'normal')
    doc.text('Generated by StokSync · Echelon Crest (PTY) LTD · Reg. 2026/420468/07', 14, pageHeight - 12)
    doc.text(`Page ${pageNum}`, 196, pageHeight - 12, { align: 'right' })
  }

  function addTable(doc, headers, rows, startY, colWidths) {
    const rowHeight = 8
    const headerHeight = 9
    let y = startY

    // Header row
    doc.setFillColor(240, 253, 244)
    doc.rect(14, y, 182, headerHeight, 'F')
    doc.setDrawColor(29, 158, 117)
    doc.setLineWidth(0.3)
    doc.rect(14, y, 182, headerHeight, 'S')

    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 58, 87)
    let x = 16
    headers.forEach((h, i) => {
      doc.text(h, x, y + 6)
      x += colWidths[i]
    })
    y += headerHeight

    // Data rows
    rows.forEach((row, rowIndex) => {
      if (rowIndex % 2 === 0) {
        doc.setFillColor(250, 250, 250)
        doc.rect(14, y, 182, rowHeight, 'F')
      }
      doc.setDrawColor(230, 230, 230)
      doc.setLineWidth(0.2)
      doc.line(14, y + rowHeight, 196, y + rowHeight)

      doc.setFontSize(8.5)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(50, 50, 50)
      x = 16
      row.forEach((cell, i) => {
        const cellStr = String(cell)
        // Color paid/pending
        if (cellStr === 'Paid') doc.setTextColor(22, 163, 74)
        else if (cellStr === 'Pending') doc.setTextColor(217, 119, 6)
        else doc.setTextColor(50, 50, 50)
        doc.text(cellStr, x, y + 5.5)
        x += colWidths[i]
      })
      y += rowHeight
    })

    return y + 4
  }

  // 1. Monthly Contributions Report
  async function generateMonthlyReport() {
    setGenerating('monthly')
    const jsPDF = await loadJsPDF()
    const doc = new jsPDF()

    let y = addHeader(doc, 'Monthly Contributions Report', `${group.name} · ${currentMonth}`)

    // Summary box
    const monthContribs = contributions.filter(c => c.month === currentMonth)
    const paid = monthContribs.filter(c => c.status === 'Paid')
    const pending = monthContribs.filter(c => c.status === 'Pending')
    const totalCollected = paid.reduce((s, c) => s + parseFloat(c.amount || 0), 0)

    doc.setFillColor(240, 253, 244)
    doc.roundedRect(14, y, 182, 22, 3, 3, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 58, 87)
    doc.text(`Group: ${group.name}`, 20, y + 7)
    doc.text(`Month: ${currentMonth}`, 20, y + 13)
    doc.text(`Total Members: ${members.length}`, 100, y + 7)
    doc.text(`Collected: R${totalCollected.toLocaleString('en-ZA')}`, 100, y + 13)
    doc.text(`Paid: ${paid.length}  |  Pending: ${pending.length}`, 20, y + 19)
    y += 28

    // Table
    const rows = members.map(m => {
      const contrib = monthContribs.find(c => c.member_id === m.id)
      return [
        m.payout_order || '—',
        m.name,
        m.email || '—',
        contrib ? `R${contrib.amount}` : `R${group.contribution_amount}`,
        contrib ? contrib.status : 'Not logged',
        contrib?.paid_at ? new Date(contrib.paid_at).toLocaleDateString('en-ZA') : '—',
      ]
    })

    y = addTable(doc,
      ['#', 'Member Name', 'Email', 'Amount', 'Status', 'Date Paid'],
      rows, y, [12, 45, 55, 22, 22, 26]
    )

    addFooter(doc, 1)
    doc.save(`StokSync_Monthly_${group.name}_${currentMonth}.pdf`)
    setGenerating(null)
  }

  // 2. Outstanding Members Report
  async function generateOutstandingReport() {
    setGenerating('outstanding')
    const jsPDF = await loadJsPDF()
    const doc = new jsPDF()

    let y = addHeader(doc, 'Outstanding Members Report', `${group.name} · Generated ${new Date().toLocaleDateString('en-ZA')}`)

    const pendingContribs = contributions.filter(c => c.status === 'Pending')
    const outstanding = members.map(m => {
      const pending = pendingContribs.filter(c => c.member_id === m.id)
      const total = pending.reduce((s, c) => s + parseFloat(c.amount || 0), 0)
      return { member: m, pending, total }
    }).filter(x => x.pending.length > 0)

    // Summary
    doc.setFillColor(255, 251, 235)
    doc.roundedRect(14, y, 182, 16, 3, 3, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 58, 87)
    const totalOutstanding = outstanding.reduce((s, x) => s + x.total, 0)
    doc.text(`Members with outstanding payments: ${outstanding.length}`, 20, y + 7)
    doc.text(`Total outstanding: R${totalOutstanding.toLocaleString('en-ZA')}`, 20, y + 13)
    y += 22

    if (outstanding.length === 0) {
      doc.setFontSize(12)
      doc.setTextColor(22, 163, 74)
      doc.text('All members are up to date! No outstanding payments.', 14, y + 10)
    } else {
      const rows = outstanding.map(x => [
        x.member.name,
        x.member.email || '—',
        x.member.phone || '—',
        x.pending.length.toString(),
        `R${x.total.toLocaleString('en-ZA')}`,
        x.pending.map(p => p.month).join(', '),
      ])

      y = addTable(doc,
        ['Member Name', 'Email', 'Phone', 'Months', 'Total Owed', 'Months Outstanding'],
        rows, y, [35, 40, 28, 18, 22, 39]
      )
    }

    addFooter(doc, 1)
    doc.save(`StokSync_Outstanding_${group.name}.pdf`)
    setGenerating(null)
  }

  // 3. Yearly Summary
  async function generateYearlySummary() {
    setGenerating('yearly')
    const jsPDF = await loadJsPDF()
    const doc = new jsPDF()

    let y = addHeader(doc, 'Yearly Summary Report', `${group.name} · ${currentYear}`)

    const yearContribs = contributions.filter(c => c.month?.includes(currentYear.toString()))
    const totalCollected = yearContribs.filter(c => c.status === 'Paid').reduce((s, c) => s + parseFloat(c.amount || 0), 0)

    // Summary box
    doc.setFillColor(240, 253, 244)
    doc.roundedRect(14, y, 182, 22, 3, 3, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 58, 87)
    doc.text(`Group: ${group.name}`, 20, y + 7)
    doc.text(`Year: ${currentYear}`, 20, y + 13)
    doc.text(`Total Members: ${members.length}`, 100, y + 7)
    doc.text(`Total Collected: R${totalCollected.toLocaleString('en-ZA')}`, 100, y + 13)
    y += 28

    // Month by month breakdown
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December']

    const rows = monthNames.map(month => {
      const fullMonth = `${month} ${currentYear}`
      const monthContribs = contributions.filter(c => c.month === fullMonth)
      const paid = monthContribs.filter(c => c.status === 'Paid')
      const pending = monthContribs.filter(c => c.status === 'Pending')
      const collected = paid.reduce((s, c) => s + parseFloat(c.amount || 0), 0)
      return [
        fullMonth,
        paid.length.toString(),
        pending.length.toString(),
        collected > 0 ? `R${collected.toLocaleString('en-ZA')}` : 'R0',
        monthContribs.length === 0 ? 'No data' : paid.length === members.length ? 'Complete' : 'In progress',
      ]
    })

    y = addTable(doc,
      ['Month', 'Paid', 'Pending', 'Collected', 'Status'],
      rows, y, [50, 25, 25, 42, 40]
    )

    addFooter(doc, 1)
    doc.save(`StokSync_YearlySummary_${group.name}_${currentYear}.pdf`)
    setGenerating(null)
  }

  // 4. Payout Schedule
  async function generatePayoutSchedule() {
    setGenerating('payouts')
    const jsPDF = await loadJsPDF()
    const doc = new jsPDF()

    let y = addHeader(doc, 'Payout Schedule', `${group.name} · ${currentYear}`)

    // Summary
    doc.setFillColor(240, 253, 244)
    doc.roundedRect(14, y, 182, 16, 3, 3, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 58, 87)
    doc.text(`Group: ${group.name}`, 20, y + 7)
    doc.text(`Contribution: R${group.contribution_amount}/month`, 20, y + 13)
    doc.text(`Total Members: ${members.length}`, 120, y + 7)
    doc.text(`Cycle: ${group.cycle || 'Monthly'}`, 120, y + 13)
    y += 22

    const sortedMembers = [...members].sort((a, b) => (a.payout_order || 0) - (b.payout_order || 0))
    const payoutAmount = members.length * parseFloat(group.contribution_amount || 0)

    const rows = sortedMembers.map(m => {
      const payout = payouts?.find(p => p.member_id === m.id)
      return [
        (m.payout_order || '—').toString(),
        m.name,
        m.email || '—',
        `R${payoutAmount.toLocaleString('en-ZA')}`,
        payout?.scheduled_date ? new Date(payout.scheduled_date).toLocaleDateString('en-ZA') : 'TBD',
        payout?.status || 'Upcoming',
      ]
    })

    y = addTable(doc,
      ['Order', 'Member Name', 'Email', 'Payout Amount', 'Scheduled Date', 'Status'],
      rows, y, [18, 42, 48, 28, 28, 18]
    )

    addFooter(doc, 1)
    doc.save(`StokSync_PayoutSchedule_${group.name}.pdf`)
    setGenerating(null)
  }

  // 5. Individual Member Statement (for selected member)
  async function generateMemberStatement(member) {
    setGenerating(`member-${member.id}`)
    const jsPDF = await loadJsPDF()
    const doc = new jsPDF()

    const memberContribs = contributions.filter(c => c.member_id === member.id)
    const paid = memberContribs.filter(c => c.status === 'Paid')
    const totalPaid = paid.reduce((s, c) => s + parseFloat(c.amount || 0), 0)

    let y = addHeader(doc, 'Member Statement', `${member.name} · ${group.name}`)

    // Member details box
    doc.setFillColor(240, 253, 244)
    doc.roundedRect(14, y, 182, 30, 3, 3, 'F')
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 58, 87)
    doc.text('MEMBER DETAILS', 20, y + 7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(50, 50, 50)
    doc.text(`Name: ${member.name}`, 20, y + 14)
    doc.text(`Email: ${member.email || '—'}`, 20, y + 20)
    doc.text(`Phone: ${member.phone || '—'}`, 20, y + 26)
    doc.text(`Group: ${group.name}`, 110, y + 14)
    doc.text(`Payout Order: #${member.payout_order || '—'}`, 110, y + 20)
    doc.text(`Statement Date: ${new Date().toLocaleDateString('en-ZA')}`, 110, y + 26)
    y += 36

    // Stats
    doc.setFillColor(27, 58, 87)
    doc.roundedRect(14, y, 55, 20, 3, 3, 'F')
    doc.setFillColor(29, 158, 117)
    doc.roundedRect(74, y, 55, 20, 3, 3, 'F')
    doc.setFillColor(217, 119, 6)
    doc.roundedRect(134, y, 62, 20, 3, 3, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(`R${totalPaid.toLocaleString('en-ZA')}`, 41, y + 10, { align: 'center' })
    doc.text(paid.length.toString(), 101, y + 10, { align: 'center' })
    doc.text(memberContribs.filter(c => c.status === 'Pending').length.toString(), 165, y + 10, { align: 'center' })

    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.text('Total Contributed', 41, y + 16, { align: 'center' })
    doc.text('Payments Made', 101, y + 16, { align: 'center' })
    doc.text('Pending', 165, y + 16, { align: 'center' })
    y += 26

    // Payment history table
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(27, 58, 87)
    doc.text('Payment History', 14, y + 6)
    y += 10

    const rows = memberContribs.map(c => [
      c.month,
      `R${c.amount}`,
      c.status,
      c.paid_at ? new Date(c.paid_at).toLocaleDateString('en-ZA') : '—',
    ])

    if (rows.length === 0) {
      doc.setFontSize(9)
      doc.setTextColor(150, 150, 150)
      doc.text('No contributions recorded yet.', 14, y + 6)
    } else {
      y = addTable(doc,
        ['Month', 'Amount', 'Status', 'Date Paid'],
        rows, y, [65, 40, 40, 37]
      )
    }

    addFooter(doc, 1)
    doc.save(`StokSync_Statement_${member.name}_${group.name}.pdf`)
    setGenerating(null)
  }

  const reportTypes = [
    {
      id: 'monthly',
      icon: '📅',
      title: 'Monthly Contributions',
      desc: `All member payments for ${currentMonth}`,
      color: 'bg-blue-50 border-blue-100',
      action: generateMonthlyReport,
    },
    {
      id: 'outstanding',
      icon: '⚠️',
      title: 'Outstanding Members',
      desc: 'Members with pending or missed payments',
      color: 'bg-amber-50 border-amber-100',
      action: generateOutstandingReport,
    },
    {
      id: 'yearly',
      icon: '📊',
      title: 'Yearly Summary',
      desc: `Month-by-month breakdown for ${currentYear}`,
      color: 'bg-purple-50 border-purple-100',
      action: generateYearlySummary,
    },
    {
      id: 'payouts',
      icon: '💰',
      title: 'Payout Schedule',
      desc: 'Full rotation with dates and amounts',
      color: 'bg-green-50 border-green-100',
      action: generatePayoutSchedule,
    },
  ]

  return (
    <div className="space-y-5">

      {/* Group reports */}
      <div>
        <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-3">Group Reports</h3>
        <div className="space-y-3">
          {reportTypes.map(r => (
            <div key={r.id} className={`${r.color} border rounded-2xl p-4 flex items-center justify-between`}>
              <div className="flex items-center gap-3">
                <span className="text-2xl">{r.icon}</span>
                <div>
                  <p className="font-semibold text-sm text-gray-900">{r.title}</p>
                  <p className="text-xs text-gray-500">{r.desc}</p>
                </div>
              </div>
              <button
                onClick={r.action}
                disabled={generating === r.id}
                className="flex items-center gap-1.5 px-3 py-2 bg-white border border-gray-200 rounded-xl text-xs font-medium text-gray-700 hover:border-brand hover:text-brand transition-colors disabled:opacity-60 flex-shrink-0"
              >
                {generating === r.id ? (
                  <div className="w-3 h-3 border border-brand border-t-transparent rounded-full animate-spin"/>
                ) : (
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                    <path d="M6 1v7M3 5l3 3 3-3M1 10h10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                  </svg>
                )}
                {generating === r.id ? 'Generating...' : 'Download PDF'}
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Individual member statements */}
      <div>
        <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wide mb-3">Member Statements</h3>
        <div className="bg-white rounded-2xl border border-gray-100 divide-y divide-gray-50">
          {members.length === 0 ? (
            <p className="text-center text-gray-400 text-sm py-6">No members yet</p>
          ) : (
            members.map(m => (
              <div key={m.id} className="flex items-center justify-between px-4 py-3">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-full bg-brand-light flex items-center justify-center flex-shrink-0">
                    <span className="text-brand font-semibold text-sm">{m.name.charAt(0).toUpperCase()}</span>
                  </div>
                  <div>
                    <p className="font-medium text-sm text-gray-900">{m.name}</p>
                    <p className="text-xs text-gray-400">
                      {contributions.filter(c => c.member_id === m.id && c.status === 'Paid').length} payments · 
                      R{contributions.filter(c => c.member_id === m.id && c.status === 'Paid').reduce((s, c) => s + parseFloat(c.amount || 0), 0).toLocaleString('en-ZA')} total
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => generateMemberStatement(m)}
                  disabled={generating === `member-${m.id}`}
                  className="flex items-center gap-1.5 px-3 py-2 bg-brand-light border border-brand/20 rounded-xl text-xs font-medium text-brand hover:bg-brand hover:text-white transition-colors disabled:opacity-60 flex-shrink-0"
                >
                  {generating === `member-${m.id}` ? (
                    <div className="w-3 h-3 border border-brand border-t-transparent rounded-full animate-spin"/>
                  ) : (
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                      <path d="M6 1v7M3 5l3 3 3-3M1 10h10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                    </svg>
                  )}
                  {generating === `member-${m.id}` ? 'Generating...' : 'Statement'}
                </button>
              </div>
            ))
          )}
        </div>
      </div>

    </div>
  )
}